---
title: "Some Categories"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(collapsibleTree)
library(gapminder)
library(tidyverse)
library(plotly)
library(ggthemes)
data(gapminder)
gapminder <-  gapminder %>%
  filter(year == max(year)) %>%
  arrange(-pop) %>%
  slice(1:50) %>%
  mutate(GDP = gdpPercap*pop)
```

Column {data-width=450}
-----------------------------------------------------------------------

### GDP vs. Population

```{r}
p <- ggplot(gapminder, 
       aes(x = pop, y = GDP, color = continent)) + 
  geom_point() + 
  scale_x_log10(labels = function(x) scales::number(x, scale = 1/1000000)) + 
  scale_y_log10(labels = function(x) scales::dollar(x, scale = 1/1000000000, accuracy = 1)) + 
  theme_tufte() + 
  guides(color = FALSE) + 
  labs(x=  "Population (Millions)", y = "GDP (Billions)") +
  annotate(geom = 'label', x = 300000000, y = 500000000000, label = 'Unsurprisingly, bigger\ncountries have bigger GDPs', hjust= 0, vjust = 0)
p
```

### Chart B

```{r}
ggplotly(p)
```

Column {data-width=550}
-----------------------------------------------------------------------

### Percentage of GDP and Continent GDP

```{r}
gapminder %>%
  collapsibleTreeSummary(
    hierarchy = c("continent","country"),
    root = "50 Biggest Countries",
    percentOfParent = TRUE,
    width = 800,
    attribute = "GDP",
    zoomable = FALSE
  )
```

